### ISSUE TITLE
Spec : extension name in the table

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#10]
All tables of  extension descriptors have "Extension name" at the first row.
It seems like the extension name is a descriptor or is it a descriptor?

If I understand correctly, a descriptor describes the meaning of a value. for example, 
descriptor - gain
value -  0.3 
then we understand 0.3 describes how loud it is.

However extension name is used as a value. for example

> \<extension>trajectory\</extension>

this statement toggle the boolean value.

**Comment by j45ch** [comment]
fixed:
moved etension name to top of all tables, set off by double line, then followed by descriptor labels and values

made all tables end in single line
