### ISSUE TITLE
Table 14: consistency  

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#14]
I assume the default value of group name is NULL or not defined thus it is \<none>.

I could be better to define the convention in this case.
If we use <none> here, the **unique identifier** in table 8 should be \<unique identifier>

and **none** is reserved word for group-membership descriptor not name descriptor so it might be confusing if we use \<none> in the table of group descriptors.

**Comment by j45ch** [comment]
syncronised point anf grop descrition, in both cases UNique identifier as escriptor name and (unique id!) as default value: better ideas?
