### ISSUE TITLE
Spec : 5.4 private extension 

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#16]
> The private extension serves as a generic container to store statements which are renderer specific and not covered within the SpatDIF specification. A private extension has to be declared with private and an individual descriptor (e.g., the name of the renderer). The use of a private extension must be declared with the extensions descriptors of the meta data.

I assume it means I should write
\<extension>private\<\\extension>

but the extension name of the private extension is unclear in this description.
It is of course redundant but for the formality, it would be better to add a table only with extension name entry.

**Comment by j45ch** [comment]
added, was just commented out
