### ISSUE TITLE
Spec: Table 1 descriptions of info descriptors

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#20]
- The first character of the descriptions of descriptors are sometimes not capitalised.
- in the info section duration descriptor is duplicated and no explanation found about that
- the definition of "session" is (to me) a little bit ambiguous 
-  Description of ordering

> how is the time section is organized

should be

how the time section is organized

**Comment by j45ch** [comment]
uppercase fixed

added:
"The duration descriptor can have two different data-types (double or string), for consistency, the same style should be used throughout a SpatDIF scene."

and OR in the descriptor list

**Comment by j45ch** [comment]
added better description to 'session' descriptor, needed to have different versions of the same piece at the same date/location etc.

corrected ordering description
