### ISSUE TITLE
bool - boolean inconsistency in many places

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#27]
still "boolean" is used in the following three descriptors.

Table 3 / present
Table 14 /present
Table 18 / present 

this should be replaced by **bool**

**Comment by lossius** [comment]
Closed in 53764b048d2d6bfc67a7d98490c0e1d805704676

**Comment by lossius** [comment]
This issue can be closed now by someone with necessary permissions.
