### ISSUE TITLE
spec: table 14

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#28]
In table 14 , the description column is missing.
**Unique identifier** in the descriptor column should be under description column and descriptor should be "id" for the consistency.

**Comment by lossius** [comment]
I changed "Unique identifier" to "id" without adding a new Descriptor coloumn.

The default value row already says "(unique id!)" so it seems redundant to add an additional row just to say this twice. 

I believe this issue can be closed now.

What do you think @chikashimiyama ?
