### ISSUE TITLE
extension which requires extension

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#31]
I think it's more implementation question but

Trajectory Generator requires other extension descriptors.
In this case should I activate all extensions manually?

> \<extension>trajectory pointset geometry automation shape\</extension>

or just

> \<extension> trajectory\</extension>

automatically activates other necessary extensions?
if so, what's gonna happen, if I deactivate an extension which requires other extensions.

**Comment by lossius** [comment]
We need to ensure that we state explicitly in the specs what other extensions this extension depends on. Additionally we need to say that any authoring or rendering tool that supports this extension, should load all the dependency extensions as well when this one is requested.

In authored files it should be enough to specify this extension in the meta section, and the rest are then implicitly required, much in the same way as how the handling of Ruby gems are done in Bundler gemfiles.

**Comment by j45ch** [comment]
state in the trajectory section that a declaration of trajectory implicit means loading the dependent extensions; chapter 2.3.2
