### ISSUE TITLE
Why do we use "double" as a variable type?

### ISSUE THREAD

**Issue by lossius** [j45ch/sptdf04_issues#40]
In the tables throughout the specification, floating point values are specified as "double". Is "double" a data type that is used beyond the various C types of languages, or should w rather specify something alike to "64 bit float" to make it more general?

**Comment by j45ch** [comment]
perhaps we need a definition somewhere about the basic numeric data-types:
- Boolean (1 Bit)
- Integer (32 Bit)
- Floating Point (64 Bit)

Should fractional data-types have the best resolution (128bit or even **Decimal** like scaling factor)? Or the fastest resolution (64bit?)

If SpatDIF is to be future-proof, then the numeric data type should be scaleable in the future...


https://msdn.microsoft.com/en-us/library/ae55hdtk.aspx

**Comment by lossius** [comment]
Do we have any binary representations for SpatDIF files, or are all current formats text-based (such as OSC, XML, JSON and YAML)? If we only have text-based formats, the decimal numbers will anyway be represented as standard decimals. In that case it can be left to the author of the scenes what precision they want to specify.

On the other hand we should probably state that applications rendering SpatDIF files should be able to represent decimal values as a minimum of 64 bit floats.

I don't think that we need to say anything specific about boolean, there are no real ambiguities there.

**Comment by lossius** [comment]
We change this, and clarify it in a new 2.4 subsection.

**Comment by jcelerier** [comment]
>  floating point values are specified as "double". 

For reference, double is also the standard "numeric" data type used by javascript; any number that goes through JS / JSON, unless kept as a string, will be converted to double at some point.

OSC 1.0 is float instead. 

For arbitrary precision you have to use some kind of "bignum" libraries such as https://gmplib.org/ (along with the performance hit :p)

**Comment by j45ch** [comment]
thank you, jean-marc, but we are deliberately NOT speaking of software implementations here, rather we are merely describing the parameter; how a software implements this is not part of our specification.

**Comment by j45ch** [comment]
done
