### ISSUE TITLE
Loop extension : express what happens when end point < start point

### ISSUE THREAD

**Issue by lossius** [j45ch/sptdf04_issues#48]
Add a sentence that explains that this means that the loop is to play back backwards.

**Comment by lossius** [comment]
Committed.

@j45ch : Can you please review this, in particular for language as well as the following three details:

- I changed "possible values" to dash (-). Is that OK, or should we say that these values need to be set within the full range of the underlying dataset?
- We used to have a `EOF`symbol. In last Skype we decided that we need to avoid "File", as looping can be used with data structures that are not file based. Still, I feel that we need to add back in specific symbols that can be used to indicate `SOD` (start of data) and `EOD` (end of data), so that this can be specified without needing numerics. I suggest using the strings `start-of-data`and `end-of-data`rather than abbreviations. If you agree on this, please indicate and assign back to me, and I'll add it.
- In the discussion of repeat with additional int values, we state that `a repeat 3 will stop after the third repetition`. This will actually produce 4 playbacks (the first and three repeats). Is this intuitive and an ideal way of defining it? Or should weintroduce an additional value called `iterate`, so that `repeat`will go on and on, while `iterate 3`will play it threetimes over and then stop?

**Comment by j45ch** [comment]
@trond:
**point 1)** I would say: within total range of data-set (or perhaps scene duration?)

**point 2)** why is it important to have these descriptors? When in a file-based scenario, we know the last time-vale; when in a stream scenario, we can't know th elast time-vale, therefore in the first case it's redunant and in the second case it's not applicable. I would avoid it altogether....

> point 3)

 it is not intuitive, indeed. maybe we should avoid adding another descriptor and simply state: 
`number of repetitions; including the first iteration.`

**Comment by lossius** [comment]
Conclusion to (2):

We introdeuce symbols "begining" and "ending" and need to do "OR" same way as in other places.

**Comment by lossius** [comment]
type => mode

The different modes are:

forward
backward
forward-backward
backward-forward
none

If `forward-backward 2` then it is to be interpredes as ´playing forward, then backward, then forward again, and finally backward.
