### ISSUE TITLE
Make it explicit that angles are described using degrees, not radians

### ISSUE THREAD

**Issue by lossius** [j45ch/sptdf04_issues#57]
This need to be added in:

- 4.3 Core Descriptors
- 5.2.2 Geometry Extension
- C : Coordinate System Conventrions
- D : Orientation System Convensions

**Comment by Nilson** [comment]
Appendix D already states "The default unit for describing orientation of entities are Euler angles **in degree**"

**Comment by Nilson** [comment]
added note to Coordinate System Conventions.
