### ISSUE TITLE
power interpolation needs to be defined in the appendix

### ISSUE THREAD

**Issue by j45ch** [j45ch/sptdf04_issues#58]
the new interpolation type `power` should be defined in appendix B Interpolation Equations
the `cubic-bezier` method should likewise be defined in the appendix, or at least a reference to a standard definition found online should be given.

**Comment by chikashimiyama** [comment]
added and pushed 
@j45ch please review and close.

**Comment by j45ch** [comment]
checked and looks good

<pre><code>
----------begin_max5_patcher----------
1062.3oc0YssbSqCE84juBc7SoGR6naVx9LCeIL.iarRQTearcJovv67L+L7
NeJ7kftXmZ.mhGGKmbdn0ijUjV6k16k1a4Osbg2s46EUdf+C7JvhEeZ4hElt
zcrno8Buzn8aRhpLCyKcWRsrJQFKJ8Vaeekntp9wDg983l9jwlQme66ul.aG
X1tz7c0Ipg2cnEQkQohZQ4aEYQ2ZmF3SScpLSA.KDg2.WCv2.Aut481oq9wB
gc.ddqU+c30GfkWGHHyZQ.5.Bp27NY1cusTro1NQDBRuV9bh9AAyzOP5VfWq
+Qed4R8+VOPVaaRtZk89SxAGNdxonTTIxpipk4YcfNk6qAKmh0OfM+64orai
xt64nss4koQl4mMRhDY.kucGDORZLS7AEo0BpZwdyh38u.zM8wsA8ysniwDp
cIsQNPuG7e0nobqaCkci+za0uPss1mUyO2VMNT+HH3j1pOdDCyAQLlPE+P3E
TDCgQbWDSQ9G5iZ8OytNDrQkfPNIadSdZpZW9OL5XQR80ODkzmkS62x+aNNX
CRoGwwY7G+f4TCEvf142z.N4gRDWEJQC3WPgRMznaBkt9Hxv3ybrDFY1IThw
9NHV5w6K.uDrcEPgoU2eE3JvK.qtG7iu70ldt5MEfu+MPoZuUzG8fFW.GzDv
wgzINfiZmwfPyoVr.K2Q6L2ayypqjezL8H045WRjIbjjou0XgNhLY7y.YdLR
BENJRhEXSpIXp837I7tR7H2HwiBlbIdFL3BRhmxBctD++bDMdzYKU6FqFYcN
aD7OWZ7q1BVolPcGlWtcUyqupONiMRsJS7GivcjVkkCmYsJ8EazCE4ONkJtI
tjL4x4MJUHJrSx4vI1YSAk9nhwkWNCYgZ.Yp8Vr2GTKU.cBUbOXkLKVru2vG
73BeZpmvd0PSHgPHFgHdn81xbzgXNnNEFytCRufpSAYOY8DOD6XtUE8wriKy
QNyVmNBOwtSLnobEq6DxQk8hPSt6TKgPuHtAoFVDA4NzcZiP12MoLxrrs5pX
a9LS+YWVGJbnSzqUNZ4k8PEAOOUbBmBw5H5RntIJ4Dtl0Y1cuM+jIwc+n7A8
+M7AkMCmlzVbvdi2uI2+CUGbnq15CVsWqVzo.gm9U8kjC1YAN1i64gi4hILi
wKQl86evTyBo6+Wowp7ckaZ2wa+VefmVpXQUsLynD1YP5uVZmA8NYbrHqq0G
Kqz9WF1p+ZQFLdBF.d9MP6T7vGBdBlM7fBFJdPyBdnCAN7YCN5OD2vvyL493
OD7vlO2GzPvi+7seQFJdfWLtyn4y8gMT3LO6VngHFhBtn1szeyq4hdHCEOyj
3CdH3gLR7XS8Hpn3AQYUybZfhJWs2qp8P0ju1zTlYaRLMKEOHaGuYM7hJU4D
UqRHZWoMEp8Lahsdo4whxrcRSlOK0q7mW9Sf1Xeqe
-----------end_max5_patcher-----------
</code></pre>
