### ISSUE TITLE
Table7: spatial_trajectory.xml + pointset

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#63]
the example spatial_trajectory.xml contains a core functionality descriptor "interpolation" within pointset definition.
However "interpolation" is not included in table 7. 
This descriptor should be clearly included in table 7 because 
1. it is mandatory to define the the relationships between points
2. Table 9 includes the loop descriptor. so the exclusion of the core descriptor creates incoherence.

**Comment by Nilson** [comment]
I don't think that the interpolation method should be part of Table 7. This table defines the point set positions - this is orthogonal to the way these points are interpreted in time. Section 5.3.1.1 (Trajectory Generator) specifies how a trajectory in time is defined by combining point set and interpolation. the example spatial_trajectory.xml should be reviewed to keep alignment with the specs.

**Comment by j45ch** [comment]
we're reworking interpolation into a core function and an extended set of decriptors
