### ISSUE TITLE
Distinguishing  dataset extension from other extension

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#64]
some core-functionality and extensions, which have an "id" descriptor in the table,  such as pointset, media, etc.  can declare sets of data in the meta section and these datasets are indexed with unique ids, but the extensions without id descriptor are unable to do that.  

It clearly reflects our design-philosophy. e.g. pointset can be named but trajectory cannot be named (because no id descriptor for trajectory). So if you want to have exactly same trajectory for two different entities at the same time you have to repeat the same instruction for different two entities again. 

so I think it's very important design decision. Thus, it is important to state (ideally directly under the section title of each extension in the spec. ) whether the dataset of extension can be defined in the meta section with an unique identifier.

**Comment by j45ch** [comment]
added to **id** descriptor line 481
