### ISSUE TITLE
interpolation power with parameter table 5

### ISSUE THREAD

**Issue by j45ch** [j45ch/sptdf04_issues#65]
But in this case we need to change the data type of interpolation from

1 string 

to

1 string + (1 decimal )

in table 6 ( like the type descriptor of loop core functionality in table 5)

**Comment by Nilson** [comment]
would there be also other parameter necessary for the interpolation type "cubic-bezier" ?

**Comment by Nilson** [comment]
also, should there be a default value for the power parameter in case there is no additional decimal? e.g., p=1?
