### ISSUE TITLE
scene defaults in the meta section

### ISSUE THREAD

**Issue by j45ch** [j45ch/sptdf04_issues#69]
In general I have to say I am uneasy with your concept of placing as many default elements of the scene as possible into the meta-section. This gives the impression that the scene is already described. It is not, because the realisation of a scene MUST ALWAYS happen in the time section. So I think that instead of filling the meta-section with the default state and positions of the scene, this could/should happen at time 0.0 in the time-section. As a rule, everything that is a template is defined in the meta-section, but everything that will be played back MUST be in the time-section. I fear that otherwise a static scene can be entirely described in the meta-section, and then the playback-mechanism will have nothing to play without knowing that the meta-defaults also define the scene.

**Comment by chikashimiyama** [comment]
I would like  to mention three things regarding this issue:

1) Section 2.2.1

> As a rule, everything that is a template is defined in the meta-section, but everything that will be played back MUST be in the time-section. . I fear that otherwise a static scene can be entirely described in the meta-section ...

Then, the statement in the section 2.2.1 might be misleading.

> The Meta Section contains meta descriptions, and is located at the beginning of a SpatDIF represen- tation. It contains information that is not executed at runtime; timed events are therefore excluded from this section. The Meta descriptions contain extension setup information (see Section 5), general annotation and documentation information, information about the organization of the subsequent time section, higher-level process and compositional information and technical setup information referring to the original authoring situation. The Meta Section can also be used to describe a **static scene** or the **initial state of a dynamic scene**. The Meta Section is mandatory for a SpatDIF representation.

This statement can be interpreted that a static scene can be described **solely** with the meta section.

2)
It reminds me of old MIDI sequencers; we had to send extremely many MIDI messages (program change, control number etc.) to set up an external sound module at time 0.0 and some sound modules was not able to handle them in time. So many MIDI composers distributed initialization message within measure 1 and they start their piece from measure 2. And this problem may also occur if we put accumulative initialization instructions (e.g. if we use 100 entities for the scene ) at time 0.0.  

Of course, you could argue this is a problem of the renderer not the spec and I understand the idea that "meta" section is for defining "meta" things like pointset not the place for initialization. But the place for initialization is practically convenient from the view of the developer.

**Comment by Nilson** [comment]
I agree with Chikashi, the specs clearly indicate that the meta section can be used for setting the initial state of the dynamic scene. Can we prevent the potential scenario that the playback-mechanism will have nothing to play? Considering that many descriptors have default values (e.g., position, gain, ...) wouldn't the scene start playing even if there are no other initialization values set?

**Comment by chikashimiyama** [comment]
I think we need to refer the name media template in the time section at least once in order to associate defined media and the time. so empty time section doesn't happen, if we need to playback something. 

On the other hand, the Zirkonium Speaker Setup software exports speaker setup XML file in SpatDIF format, which consists of only the meta section.
```
<time>0.0</time>
<myEntity>
   <media>mysound_file1</media>
</myEntity>
```

**Comment by j45ch** [comment]
a more precise description of pre-loading in meta:

2.2.1 Meta Section
The Meta Section can also be used to describe a static scene or the initial state of a dynamic scene

**Comment by j45ch** [comment]
added a few clarifications, closing
