### ISSUE TITLE
templating, name for id-based data referencing

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#72]
We can define  sets of data in the meta section, give a name (id) to it, and refer it in the time section.
This technique should have a clear name (template? predefinition? dataset?) and should be described in 2.2.1.

**Comment by chikashimiyama** [comment]
draft

**Template and id **

A core functionality and a few extensions offer a descriptor called id. This id descriptor is a unique string and can be used to name the set of values that other descriptors within the media core functionality or the extension hold. This technique is called **templating**. The definition of template is usually included in the meta section but can also be dynamically specified in the time section. The templatized set of values can be referred by the id string after the definition. The name space of the id is within the core functionality or the extension i.e. the identical id can be used twice in a single SpatDIF scene if the referring set of descriptors of the id is different.

**Comment by j45ch** [comment]
after a short discussion between Chiakshi and me on 20161028 clarified that a unique id is unique to **the entire namespace**, i.e., scene, so no duplicates inside different extensions.

**Comment by j45ch** [comment]
line 482 
% can we re-specify only single aspects of a template, thus overwriting the one set in the template?

**Comment by j45ch** [comment]
0.4 can't overwrite pre-defined id-based templates
