### ISSUE TITLE
Spec : table 13 order

### ISSUE THREAD

**Issue by chikashimiyama** [j45ch/sptdf04_issues#9]
The order of  enumeration  in the list 

– An pointset (see 5.2.1) OR a predefined shape-template (see 5.2.4).
– An interpolation method describing how to get from point to point (see 4.4.3).
– An a ne geometry transformations (see 5.2.2).
– An automation function, used in the time-section when rendering to the scene description layer
(see 5.2.3).

but in the table

- pointset
- interpolation
- automation
- shape
- geometry

the last two items are reversed
are there any reason for that? and is the horizontal separator between automation and shape necessary?

**Comment by j45ch** [comment]
fixed and added shape to listing
